services:
  minecraft-tekkit:
    build: .
    ports:
      - "31415:31415"
      - "25565:25565"
    volumes:
      - "mc-tekkit:/tekxit"
      - "./server.properties:/tekxit/server.properties"
      - "./ops.json:/tekxit/ops.json"
#     - "./banned-ips.json:/tekxit/banned-ips.json"
#     - "./banned-players.json:/tekxit/banned-players.json"
#     - "./usercache.json:/tekxit/usercache.json"
#     - "./whitelist.json:/tekxit/whitelist.json"
    environment:
      EULA: "TRUE"
      INIT_MEM: "4G"
      MAX_MEM: "8G"
    restart: "no"
    labels:
      - "--nogui"
volumes:
  mc-tekkit: {}
