services:
  minecraft-tekkit:
    build: .
    ports:
      - "31415:31415"
    volumes:
      - "mc-tekkit:/data"
#      - "./server.properties:/data/server.properties"
    environment:
      EULA: "TRUE"
      INIT_MEM: "4G"
      MAX_MEM: "8G"
    restart: "no"
    labels:
      - "--nogui"
volumes:
  mc-tekkit: {}
